### ISSUE TITLE
Got erraor and could not make this

### ISSUE THREAD

**Issue by kingtosh** [h0d/defaultapp#1]
I got error below, and could not make this.

main.swift:100:111: error: expected ',' separator
case "set" where CommandLine.argc == 4 || (CommandLine.argc == 5 && CommandLine.arguments[4] == "--simulation":
                                                                                                              ^
                                                                                                              ,
main.swift:100:111: error: expected expression in list of expressions
case "set" where CommandLine.argc == 4 || (CommandLine.argc == 5 && CommandLine.arguments[4] == "--simulation":
                                                                                                              ^
main.swift:107:6: error: expected ':' after 'case'
    }
     ^
make: *** [defaultapp] Error 1

**Comment by denrat** [comment]
My bad, this should be fixed now.
